event/urls.py
from . import views
from django.conf.urls import url
from django.urls import path

app_name = "event"
urlpatterns = [

    url(r'^$', views.home, name='home'),
    path('new/', views.create, name='new'),
    url(r'^my_events/$', views.MyEvent.as_view(), name='my_events'),
    path('my_events/delete/<int:pk>', views.delete, name='delete'),
    path('my_events/update/<int:pk>', views.update, name='update'),
    path('sync/', views.sync, name='sync'),
]

google_calendar/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('',include('event.urls'))
]

event/models.py
from django.db import models
from datetime import datetime


class Post(models.Model):
    title = models.CharField("Title", max_length=500, null=True)
    start = models.DateTimeField("Start date", default=datetime.now, null=True)  # start event date
    end = models.DateTimeField("Start date", default=datetime.now, null=True)  # end event date
    event_id = models.CharField("Event id", max_length=1024, null=True, default='N/A')  # event id from google calendar

    def __str__(self):
        return self.title

event/forms.py
from django import forms
from event.models import Post


class Event(forms.ModelForm):

    class Meta:

        model = Post
        fields = ['title', 'start', 'end', 'event_id']

event/views.py
from event.models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import  View
from django.shortcuts import render, get_object_or_404, redirect
from django.forms import ModelForm
from apiclient.discovery import build
import pickle
from event.API import GoogleCalendar



class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'start', 'end','event_id']


def home(request):
    return render(request, 'event/main.html')


def create(request, template_name='event/form.html'):
    """ Function which add new record to database and to google calendar"""
    form = PostForm(request.POST or None)
    if form.is_valid():
        title = form.data['title']
        start_time = form.data['start']
        end_time = form.data['end']
        GoogleCalendar.sent_to_API(title, start_time, end_time)

        """ assign event id to event_id filed"""
        replace = form.save(commit=False)
        replace.event_id = GoogleCalendar.get_event_id()
        replace.save()
        form.save()
        return redirect('event:home')
    return render(request, template_name, {'form': form})


class MyEvent(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):

        events = Post.objects.all()
        context = {
                'object': events
                 }
        return render(self.request, 'event/my_events.html', context)


def delete(request, pk, template_name='event/confirm_delete.html'):
    my_event = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        GoogleCalendar.delete_from_API(my_event.event_id)
        my_event.delete()
        return redirect('event:my_events')
    return render(request, template_name, {'object': my_event})


def update(request, pk, template_name='event/form.html'):
    calendar = get_object_or_404(Post, pk=pk)
    form = PostForm(request.POST or None, instance=calendar)
    if form.is_valid():
        GoogleCalendar.edit_to_API(calendar.title, calendar.start, calendar.end, calendar.event_id)
        form.save()
        return redirect('event:my_events')
    return render(request, template_name, {'form': form})


def sync(request):
    """ Establish synchronization """
    model = Post.objects.all()
    for element in model:
        model_event_id = element.event_id  #get event_id form database
        model_id = element.id # get id record
        calendar = get_object_or_404(Post, pk=model_id)
        form = PostForm(request.POST or None, instance=calendar)  # get form for element
        """ Get element from google calendar"""
        credentials = pickle.load(open("token.pkl", "rb"))
        service = build("calendar", "v3", credentials=credentials)
        result = service.calendarList().list().execute()
        calendar_id = result['items'][0]['id']
        my_event = service.events().get(calendarId=calendar_id, eventId=model_event_id).execute()

        """ Update element from google calendar to website"""
        element.start = my_event['start']['dateTime']
        replace = form.save(commit=False)
        replace.title = my_event['summary']
        replace.start = my_event['start']['dateTime']
        replace.end = my_event['end']['dateTime']
        replace.save()

    return redirect('event:my_events')

event/templates/base.html
<!DOCTYPE html>

{% load static %}
    <html lang="en">
    <head>
        <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js "></script>
        <link href="/static/Content/main.css" rel="stylesheet">

        <nav class="navbar navbar-inverse" style="background-color:#5484ED">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a href="{% url 'event:home' %}" class="brand-header-logo js-lazy-loaded qa-js-lazy-loaded">
                        <img id="logo" src="{% static '/Images/logo.png' %}" style="width:100px;" /></a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'event:new' %}">Create event</a></li>
                        <li><a href="{% url 'event:my_events' %}">My events</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#"><span class="glyphicon glyphicon-user" ></span>
                            <span class="username" >username</span>
                        </a>
                        </li>
                        <li><a href="{% url 'event:sync' %}"><span class="glyphicon glyphicon-refresh" ></span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>


            {% block head %}
    <meta charset="UTF-8">
    <title>Google calendar</title>
            {% endblock %}

        </head>
    <body>
    {% block body %}

    {% endblock %}


    </body>

</html>

event/templates/event/confirm_delete.html
{% extends 'base.html' %}

{% block body %}

<form method="post">
    {% csrf_token %}
  <h1> Are you sure you want to delete  ?</h1>

</form>


<form method="post">
    {% csrf_token %}
    <div class = "container">
{{form.as_ul}}
    <input type="submit" value="Submit" />
    </div>
</form>


{% endblock %}

event/templates/event/form.html
{% extends 'base.html' %}
{% block body %}


<form method="post">
    {% csrf_token %}
    <div class = "container">
        <ul>
            <li> Title: {{form.title}} </li>
            <li> Start: {{form.start }} </li>
            <li> Finish: {{form.end }} </li>
            {{form.event_id.as_hidden}}

        </ul>
<button class="btn btn-primary" type="submit" value="Save">Submit</button>
    </div>
</form>

<!-- Libraries for datapicker -->
<script src ="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/2.0.1/js/bootstrap-datetimepicker.min.js" type=" text/javascript"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/2.0.1/css/bootstrap-datetimepicker.min.css" rel="stylesheet" type="text/css"/>

    <script>
        $('#id_start').datetimepicker(
        {format: 'YYYY-MM-DD HH:mm:ss'
        });
        $('#id_end').datetimepicker(
        {format: 'YYYY-MM-DD HH:mm:ss'
        });
    </script>



{% endblock %}

event/templates/event/main.html
{% extends 'base.html' %}

{% block body %}
{% load static %}
<div class = "container">
    <div class="jumbotron wow bounceInDown" style="background-color:#5484ED">
        <h1 class="display-4"> My calendar </h1>

        <p> Version 0.0 </p>
    </div>

    <div class="row">
        <div class="col-md-3 wow bounceInLeft">
            <h2>Create event</h2>

            <p>
                <a class="btn btn-default" href="{% url 'event:new' %}">Go &raquo;</a>
            </p>
        </div>
        <div class="col-md-3 wow bounceInLeft">
            <h2>My events</h2>

            <p>
                <a class="btn btn-default" href="{% url 'event:my_events' %}">Go &raquo;</a>
            </p>
        </div>


{% load static %}

    <link href="{% static 'Content/animate.css' %}" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src= "{% static 'Scripts/wow.js' %}"></script>

    <script>
        new WOW().init();
    </script>

</div>


{% endblock %}

event/templates/event/my_events.html
{% extends 'base.html' %}

{% block body %}
{% load static %}

{% block content %}

  <main>
    <div class="container">
        <div class="table-responsive text-nowrap">
    <h2>My events</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Title</th>
            <th scope="col">Start date</th>
            <th scope="col">Finish date</th>
            <th scope="col">Remove</th>
            <th scope="col">Edit</th>
        </tr>
        </thead>
        <tbody>
        {% for element in object.all %}

        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ element.title}}</td>
            <td>{{ element.start }}</td>
            <td>{{ element.end}}</td>
            <td>
                <a href="{% url 'event:delete' element.id %}"><i class="glyphicon glyphicon-trash"></i></a>
            </td>
            <td>
                <a href="{% url 'event:update' element.id %}"><i class="glyphicon glyphicon-edit"></i></a>
            </td>

        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>You don't have any events</td>
        </tr>

        {% endfor %}
        </tbody>


        </tbody>
    </table>
        </div>
    </div>
  </main>


{% endblock content %}


{% endblock %}